using System;

namespace RecyOs.MKGT_DB.Entities;

public class Fcli
{
#nullable enable
    public string? Code { get; set; }
    public string? Cod_Jde { get; set; }
    public string? Nom { get; set; }
    public string? Adr1 { get; set; }
    public string? Adr2 { get; set; }
    public string? Adr3 { get; set; }
    public string? Cp { get; set; }
    public string? Ville { get; set; }
    public string? Cod_Pay { get; set; }
    public string? Pays { get; set; }
    public string? Dvs { get; set; }
    public string? Siret { get; set; }
    public string? Ape { get; set; }
    public string? Intrc { get; set; }
    public string? Intl1 { get; set; }
    public string? Intl2 { get; set; }
    public string? Intl3 { get; set; }
    public string? T1 { get; set; }
    public string? F1 { get; set; }
    public string? T2 { get; set; }
    public string? F2 { get; set; }
    public string? T3 { get; set; }
    public string? F3 { get; set; }
    public string? Email { get; set; }
    public string? Cc { get; set; }
    public byte? Site { get; set; }
    public string? Secteur { get; set; }
    public char? Sup { get; set; }
    public DateTime? Dat_Cre { get; set; }
    public DateTime? Dat_Mdf { get; set; }
    public string? Obsf { get; set; }
    public string? Obse { get; set; }
    public decimal? Fr_G { get; set; }
    public string? Codf { get; set; }
    public char? Fac_Liv { get; set; }
    public char? F_Gp { get; set; }
    public string? Banque { get; set; }
    public string? Rib { get; set; }
    public string? Fam { get; set; }
    public string? Sfam { get; set; }
    public string? Tp_Soc { get; set; }
    public string? Grp { get; set; }
    public string? Num_Cont { get; set; }
    public string? Pie_Jte { get; set; }
    public string? Ref_Cmd { get; set; }
    public string? Ctr_H { get; set; }
    public string? Commentaire { get; set; }
    public bool? Bl_Prest { get; set; }
    public string? Ag { get; set; }
    public char? Cb { get; set; }
    public string? Mes { get; set; }
    public string? Mes_Tour { get; set; }
    public string? Cfourn { get; set; }
    public string? Mode_Reg { get; set; }
    public string? Mode_Regf { get; set; }
    public decimal? F_Pav { get; set; }
    public DateTime? Dat_Prev { get; set; }
    public string? Sm_Tva { get; set; }
    public decimal? Tva { get; set; }
    public decimal? Taux_Tvaf { get; set; }
    public byte? Idx_Mois { get; set; }
    public byte? Nb_Exp { get; set; }
    public byte? Nb_Cpt { get; set; }
    public decimal? Encours { get; set; }
    public char? Fic_Trsp { get; set; }
    public char? Fic_Exut { get; set; }
    public char? Fic_Itm { get; set; }
    public char? Fic_Strt { get; set; }
    public string? Adx_Cod { get; set; }
    public string? Adx_Fou { get; set; }
    public short? N_Enlv { get; set; }
    public string? Mod_Exd { get; set; }
    public string? Num_Exd { get; set; }
    public char? Bsdi { get; set; }
    public string? N_Cap { get; set; }
    public string? Mtf_Som { get; set; }
    public string? Usr { get; set; }
    public char? Cr_F { get; set; }
    public string? Duree { get; set; }
    public string? Cc_Cv { get; set; }
    public char? Bl_Edt { get; set; }
    public int? Jade { get; set; }
    public string? Cc_Jade { get; set; }
    public string? Cv_Tiers { get; set; }
    public string? Cv_Cc { get; set; }
    public char? Fc { get; set; }
    public string? Cod_Pays { get; set; }
    public string? Email1 { get; set; }
    public string? Email2 { get; set; }
    public string? Indc1 { get; set; }
    public string? Indc2 { get; set; }
    public string? Indc3 { get; set; }
    public short? Dist_Cli { get; set; }
    public string? Pie_Ide { get; set; }
    public string? Pie_Ldlv { get; set; }
    public DateTime? Pie_Ddlv { get; set; }
    public DateTime? Pie_Edlv { get; set; }
    public string? Cpt_Fac { get; set; }
    public string? Cpt_Ach { get; set; }
    public string? Ref_Fc { get; set; }
    public string? Ref_Ac { get; set; }
    public string? Ptb1 { get; set; }
    public string? Ptb2 { get; set; }
    public string? Ptb3 { get; set; }
    public string? Cpt_Leg { get; set; }
    public string? A_Code { get; set; }
    public char? Frn_Cli { get; set; }
    public char? Deb_Enc { get; set; }
    public decimal? Mnt_Cv { get; set; }
    public decimal? Taux_Esc { get; set; }
    public string? Enc_Tiers { get; set; }
    public string? Region { get; set; }
    public string? Gr_Trf { get; set; }
    public char? Cl_Stock { get; set; }
    public string? Fi_Fed { get; set; }
    public char? Tp_Gest { get; set; }
    public char? Fc_Neg { get; set; }
    public string? Typ_Idt { get; set; }
    public string? Dat_Nais { get; set; }
    public string? N_Clv { get; set; }
    public char? Tx_Cm { get; set; }
    public string? Prn { get; set; }
    public char? Pds_Chg { get; set; }
    public char? Frn_Cc { get; set; }
    public string? Titre { get; set; }
    public string? Nm_Usage { get; set; }
    public string? Dpt_Nais { get; set; }
    public string? Lieu_Nais { get; set; }
    public char? Fic_Etpr { get; set; }
    public decimal? Cap_P { get; set; }
    public DateTime? Dt_Blc { get; set; }
    public char? Fic_Rcr { get; set; }
    public string? C_Auto { get; set; }
    public char? Pr_Pf { get; set; }
    public string? N1_Nom { get; set; }
    public string? N2_Nom { get; set; }
    public char? A_Gp { get; set; }
    public string? Nom_C { get; set; }
    public string? Ad1_C { get; set; }
    public string? Ad2_C { get; set; }
    public string? Ad3_C { get; set; }
    public string? Cp_C { get; set; }
    public string? Vil_C { get; set; }
    public string? Pay_C { get; set; }
    public string? Intl_C { get; set; }
    public string? Nom_F { get; set; }
    public string? Ad1_F { get; set; }
    public string? Ad2_F { get; set; }
    public string? Ad3_F { get; set; }
    public string? Cp_F { get; set; }
    public string? Vil_F { get; set; }
    public string? Pay_F { get; set; }
    public string? Intl_F { get; set; }
    public string? Obs_Ec { get; set; }
    public string? Bqe_Def { get; set; }
    public char? W_Sh { get; set; }
    public string? Zn_Cli { get; set; }
    public string? Aev_Id { get; set; }
    public string? Tva_Lx { get; set; }
    public string? Cl_Rsq { get; set; }
    public char? Sd_Pes { get; set; }
    public string? Nom_M { get; set; }
    public string? Adr1_M { get; set; }
    public string? Adr2_M { get; set; }
    public string? Adr3_M { get; set; }
    public string? Cp_M { get; set; }
    public string? Vil_M { get; set; }
    public string? Tel_M { get; set; }
    public string? Fax_M { get; set; }
    public string? Intl_M { get; set; }
    public string? Email_M { get; set; }
    public string? Ptb_M { get; set; }
    public char? Loc_Tour { get; set; }
    public decimal? Fact_Min { get; set; }
    public char? Rfc_Obg { get; set; }
    public string? Id_Cliext { get; set; }
    public char? Rfc_Obge { get; set; }
    public string? Grp_Attrb { get; set; }
    public string? Grp_Prm { get; set; }
    public string? N_Rue { get; set; }
    public string? Bis_Ter { get; set; }
    public string? Gps_Lat { get; set; }
    public string? Gps_Lgt { get; set; }
    public string? I_Ban { get; set; }
    public string? B_Ic { get; set; }
    public int? Cle_Ext { get; set; }
    public char? Tri_Fc { get; set; }
    public char? Fr_Cd { get; set; }
    public char? Fr_Sr { get; set; }
    public char? Fr_Dc { get; set; }
    public char? Fr_Pv { get; set; }
    public char? Fr_Ta { get; set; }
    public string? Soc_Cs { get; set; }
    public string? Soc_Mq { get; set; }
    public char? Soc_Autec { get; set; }
    public string? Cd_Pt1 { get; set; }
    public string? Cd_Pt2 { get; set; }
    public string? Inf_L1 { get; set; }
    public string? Inf_L2 { get; set; }
    public char? Fr_Cfr { get; set; }
    public char? Id_Siege { get; set; }
    public byte? Abo_Ext { get; set; }
    public string? Inf_1 { get; set; }
    public string? Inf_2 { get; set; }
    public string? Inf_3 { get; set; }
    public string? Inf_4 { get; set; }
    public string? Inf_5 { get; set; }
    public char? Pbc_Prv { get; set; }
    public char? Mod_Dfs { get; set; }
    public string? Anx_Dfs { get; set; }
    public string? Gid { get; set; }
    public string? Ecofolio { get; set; }
    public string? I_Gs { get; set; }
    public char? Fr_Go { get; set; }
    public string? P_Rt { get; set; }
    public char? Cr_Track { get; set; }
    public string? Rcp_Neg { get; set; }
    public DateTime? Rcpneg_Vd { get; set; }
    /*Cette methode permet de mettre à jour les attributs de la classe Fcli
     * avec les valeurs d'un objet de type Fcli passé en paramètre.
     * Seuls les attributs non null de l'objet passé en paramètre sont mis à jour.
     */
    #nullable disable
}




